server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    types {
        application/javascript js mjs;
        text/css               css;
        text/html              html;
        image/svg+xml          svg;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
